### ISSUE TITLE
PNPM support

### ISSUE THREAD

**Issue by JulianCataldo** [BePo65/license-report#84] opened 2022-05-29 11:23 UTC
Right now, only npm and yarn lock files are supported

**Comment by BePo65** [comment] 2022-05-30 04:22
~~I don't see a way to use both systems at the same time (and this way get a pnpm-lock.yaml file)
Even pnpm users can consume this program or why do you need a pnpm (besides using pnpm for your projects)?~~

Do You mean: support `pnpm-lock.yaml` (and when you are at it `yarn.lock` too)?

**Comment by JulianCataldo** [comment] 2022-05-31 21:37
Hello !
Yes that's it.
I've only use license-report alongside yarn in the past lol.
Didn't know it wasn't supposed to support it 🤔
Is the lock-file mandatory ? Direct dep' and 1-level depth could suffice with only package.json maybe ?

**Comment by BePo65** [comment] 2022-06-01 05:01
The problem is, where to find the installed version; package.json only gives a rough orientation for that :-). So instead of scanning the node_modules folder and as it is a good practice to use a lock file, I took the package-lock.json, but this makes it not usable for users of other installation systems.

I have to look, if I find a better solution without bloating the whole program - so give me some time.

**Comment by BePo65** [comment] 2022-07-05 05:26
fixed by pr #95

**Closed as completed by BePo65** 2022-07-05 05:26 UTC
Labels: enhancement
