### ISSUE TITLE
Add "output" file into config

### ISSUE THREAD

**Issue by WuglyakBolgoink** [BePo65/license-report#103] opened 2022-07-25 13:03 UTC
it will be great to have an additional output-path property for exporting data directly into this file and not use manualy pipes in the console outputs to concatenate results.

example:
![image](https://user-images.githubusercontent.com/2271337/180782609-9c642284-0b1b-40ed-8168-9c3cedc863b1.png)

And then anyone can change it, e.g.:

```json
{
  "fields": [
     ...
  ],
  "output": "html",
  "outputPath": "./src/dependencies.html"
}
```

currently, I need to specify the config file manually:

```json
    "build:license-report": "license-report --config=.license-report-config  > ./src/dependencies.html"
```

but with this config I will just call

```json
    "build:license-report": "license-report --config=.license-report-config"
```

and license-report should create a file

**Comment by BePo65** [comment] 2022-07-25 18:01
duplicate of issue #88

**Comment by BePo65** [comment] 2022-07-26 03:56
Can't you use a script in the package.json of the project under inspection?

**Closed as completed** 2022-10-06 04:43 UTC
Labels: duplicate, enhancement, wontfix
